[tool.poetry]
name = "aiogram-forms"
version = "0.3.0"
description = "Forms for aiogram"
authors = ["Ivan Borisenko <i.13g10n@icloud.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://pypi.org/project/aiogram-forms"
repository = "https://github.com/13g10n/aiogram-forms"
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Plugins",
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10"
]
keywords = ["aiogram", "telegram", "forms"]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7.2"
aiogram = "^2.13"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pylint = "^2.15.4"
parameterized = "^0.8.1"
pytest-asyncio = "^0.19.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
