name: CI
on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        run: poetry install
      - name: Lint project files with pylint
        run: poetry run pylint aiogram_forms
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        run: poetry install
      - name: Run tests with pytest
        run: poetry run pytest tests
