name: CI
on: pull_request

jobs:
  lint:
    name: Lint & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        run: pip install poetry==1.2.2
      - name: Install dependencies
        run: poetry install
      - name: Lint project files with pylint
        run: poetry run pylint aiogram_forms
      - name: Run tests with pytest
        run: poetry run pytest tests
